name: Go
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  deploy:
    uses: dagger/dagger-for-github/.github/workflows/deploy.yaml@v6
    with:
      verb: call
      module: github.com/shykes/daggerverse/hello
      args: hello --greeting Hola --name Jeremy
      cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
