name: Go
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push, pull_request]

jobs:
  deploy:
    name: Hello  # Properly indented 'name'
    uses: dagger/dagger-for-github@v6
    with:
      verb: call
      module: github.com/shykes/daggerverse/hello
      args: hello --greeting Hola --name Jeremy
      cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
